# Generated by Django 5.0.1 on 2024-04-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagor_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagoruser',
            name='phone_number',
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
