# Generated by Django 5.0.1 on 2024-04-29 13:20

import django.db.models.deletion
import sagor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted on')),
                ('name', models.CharField(default=sagor.models._generate_farm_name, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted on')),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('ERROR', 'Error')], default='OK', max_length=250)),
                ('last_checked_at', models.DateTimeField(auto_now=True, verbose_name='Last checked at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted on')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error')], default='INACTIVE', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted on')),
                ('broker_url', models.URLField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('ERROR', 'Error')], default='OK', max_length=250)),
                ('mac_address', models.CharField(blank=True, max_length=250, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='sagor.farm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraSensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted on')),
                ('reading_status', models.CharField(choices=[('SANE', 'Sane'), ('NOT_SANE', 'Not sane')], default='SANE', max_length=250)),
                ('read_every', models.IntegerField(default=1000)),
                ('value', models.BinaryField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_sensor_readings', to='sagor.package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PHSensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted on')),
                ('reading_status', models.CharField(choices=[('SANE', 'Sane'), ('NOT_SANE', 'Not sane')], default='SANE', max_length=250)),
                ('read_every', models.IntegerField(default=1000)),
                ('value', models.DecimalField(decimal_places=10, max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_sensor_readings', to='sagor.package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PumpedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted on')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('ERROR', 'Error')], default='OK', max_length=250)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumped_food', to='sagor.pump')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted on')),
                ('fish_type', models.CharField(choices=[('TILAPIA', 'Tilapia')], default='TILAPIA', max_length=250)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('UNHEALTHY', 'Unhealthy')], default='HEALTHY', max_length=250)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanks', to='sagor.gateway')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pump',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumps', to='sagor.tank'),
        ),
        migrations.AddField(
            model_name='package',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='sagor.tank'),
        ),
        migrations.CreateModel(
            name='TempratureSensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted on')),
                ('reading_status', models.CharField(choices=[('SANE', 'Sane'), ('NOT_SANE', 'Not sane')], default='SANE', max_length=250)),
                ('read_every', models.IntegerField(default=1000)),
                ('value', models.DecimalField(decimal_places=10, max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temprature_sensor_readings', to='sagor.package')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
