# Generated by Django 5.0.1 on 2024-04-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_status', models.CharField(choices=[('SANE', 'Sane'), ('NOT_SANE', 'Not sane')], default='SANE', max_length=250)),
                ('run_every', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_url', models.URLField()),
                ('ip', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('ERROR', 'Error')], default='OK', max_length=250)),
                ('mac_address', models.CharField(max_length=250)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='sagor.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('ERROR', 'Error')], default='OK', max_length=250)),
                ('last_checked_at', models.DateTimeField()),
                ('tank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='sagor.package')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error')], default='INACTIVE', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PumpedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('ERROR', 'Error')], default='OK', max_length=250)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumped_food', to='sagor.pump')),
            ],
        ),
        migrations.CreateModel(
            name='Tanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_type', models.CharField(choices=[('TILAPIA', 'Tilapia')], default='TILAPIA', max_length=250)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('UNHEALTHY', 'Unhealthy')], default='HEALTHY', max_length=250)),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanks', to='sagor.gateway')),
            ],
        ),
        migrations.DeleteModel(
            name='SagorUser',
        ),
        migrations.CreateModel(
            name='CameraSensor',
            fields=[
                ('basesensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sagor.basesensor')),
                ('value', models.BinaryField()),
            ],
            bases=('sagor.basesensor',),
        ),
        migrations.CreateModel(
            name='PHSensor',
            fields=[
                ('basesensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sagor.basesensor')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('sagor.basesensor',),
        ),
        migrations.CreateModel(
            name='TempratureSensor',
            fields=[
                ('basesensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sagor.basesensor')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('sagor.basesensor',),
        ),
        migrations.AddField(
            model_name='basesensor',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='sagor.package'),
        ),
        migrations.AddField(
            model_name='pump',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumps', to='sagor.tanks'),
        ),
    ]
