# Generated by Django 5.0.1 on 2024-06-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagor', '0002_alter_phsensorreading_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpedfood',
            name='pumped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pumpedfood',
            name='should_pump_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pumpedfood',
            name='status',
            field=models.CharField(choices=[('OK', 'Ok'), ('PENDING', 'Pending'), ('ERROR', 'Error')], default='OK', max_length=250),
        ),
    ]
